# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20170301_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(choices=[('DHL', 'DHL International'), ('FX', 'FedEx')], max_length=100),
        ),
    ]
