# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('GB', 'United Kingdom'), ('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BM', 'Bermuda'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('RU', 'Russian Federation'), ('US', 'United States')], max_length=100, null=True),
        ),
    ]
