# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170320_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
