# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 5Mb', null=True, upload_to='item', validators=[item.models.validate_image]),
        ),
    ]
