# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20170315_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('34', '34'), ('36', '36'), ('38', '38')], max_length=20, null=True),
        ),
    ]
