# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_amazon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
