# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20170319_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
