# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_item_medium_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='medium_image',
            new_name='thumbnail_image',
        ),
    ]
