# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20170320_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
