INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (1, 'Men', 'men', '1', 'dist/img/830b5257d4692ba.png', null);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (2, 'Women', 'women', '', 'Фото_11.03.17_12.53_ДП_3.jpg', null);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (3, 'Shoes', 'shoes', '', '', 1);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (4, 'Shirts', 'shirts', '', '', 1);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (5, 'Jackets', 'jackets', '', '', 1);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (6, 'Pants', 'pants', '', '', 1);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (7, 'Shoes', 'shoes', '', '', 2);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (8, 'Dresses', 'dresses', '', '', 2);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (9, 'Tights', 'tights', '', '', 2);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (10, 'Shorts', 'shorts', '', '', 2);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (13, 'Garden', 'garden', null, null, 11);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (12, 'Kitchen', 'Kitchen', null, null, 11);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (11, 'Home&Garden', 'homegarden', null, null, null);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (14, 'Bath', 'bath', null, null, 11);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (15, 'Decor', 'decor', null, null, 11);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (17, 'Wine', 'wine', null, null, 16);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (18, 'Vinyl', 'vinyl', null, null, 16);
INSERT INTO category_category (id, name, slug, sort_order, image, parent_category_id) VALUES (16, 'Coming soon', 'comingsoon', null, null, null);