# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170301_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(choices=[('Credit', 'Credit Card'), ('Cash', 'Cash')], max_length=50),
        ),
    ]
