# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topis', models.CharField(choices=[('Product', 'Question about product'), ('Shipment', 'Problem with order shipment'), ('Advet', 'Advertisement'), ('Other', 'Other questions')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
