# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='topis',
            field=models.CharField(choices=[('Product', 'Question about product'), ('Shipment', 'Problem with order shipment'), ('Advet', 'Advertisement'), ('Other', 'Other questions')], max_length=100, verbose_name='Topics'),
        ),
    ]
