# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
