# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20170301_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='src/media/'),
        ),
    ]
