# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('payment', '0001_initial'),
        ('cart', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField()),
                ('summary', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CartOrder')),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Delivery')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
