# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170301_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
