# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170323_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='cart_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
