# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170323_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
