# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170323_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
